yomu.modules.achievements.datasource.url=${YOMU_MODULES_ACHIEVEMENTS_DATASOURCE_URL}
yomu.modules.achievements.datasource.username=${YOMU_MODULES_ACHIEVEMENTS_DATASOURCE_USERNAME}
yomu.modules.achievements.datasource.password=${YOMU_MODULES_ACHIEVEMENTS_DATASOURCE_PASSWORD}
yomu.modules.achievements.datasource.driver-class-name=${YOMU_MODULES_ACHIEVEMENTS_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

yomu.modules.auth.datasource.url=${YOMU_MODULES_AUTH_DATASOURCE_URL}
yomu.modules.auth.datasource.username=${YOMU_MODULES_AUTH_DATASOURCE_USERNAME}
yomu.modules.auth.datasource.password=${YOMU_MODULES_AUTH_DATASOURCE_PASSWORD}
yomu.modules.auth.datasource.driver-class-name=${YOMU_MODULES_AUTH_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

yomu.modules.clan.datasource.url=${YOMU_MODULES_CLAN_DATASOURCE_URL}
yomu.modules.clan.datasource.username=${YOMU_MODULES_CLAN_DATASOURCE_USERNAME}
yomu.modules.clan.datasource.password=${YOMU_MODULES_CLAN_DATASOURCE_PASSWORD}
yomu.modules.clan.datasource.driver-class-name=${YOMU_MODULES_CLAN_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

yomu.modules.forum.datasource.url=${YOMU_MODULES_FORUM_DATASOURCE_URL}
yomu.modules.forum.datasource.username=${YOMU_MODULES_FORUM_DATASOURCE_USERNAME}
yomu.modules.forum.datasource.password=${YOMU_MODULES_FORUM_DATASOURCE_PASSWORD}
yomu.modules.forum.datasource.driver-class-name=${YOMU_MODULES_FORUM_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

yomu.modules.learning.datasource.url=${YOMU_MODULES_LEARNING_DATASOURCE_URL}
yomu.modules.learning.datasource.username=${YOMU_MODULES_LEARNING_DATASOURCE_USERNAME}
yomu.modules.learning.datasource.password=${YOMU_MODULES_LEARNING_DATASOURCE_PASSWORD}
yomu.modules.learning.datasource.driver-class-name=${YOMU_MODULES_LEARNING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

server.forward-headers-strategy=framework
