yomu.modules.achievements.datasource.url=jdbc:h2:file:./.localdb/achievements;MODE=PostgreSQL;AUTO_SERVER=TRUE
yomu.modules.achievements.datasource.driver-class-name=org.h2.Driver
yomu.modules.achievements.datasource.username=sa
yomu.modules.achievements.datasource.password=

yomu.modules.auth.datasource.url=jdbc:h2:file:./.localdb/auth;MODE=PostgreSQL;AUTO_SERVER=TRUE
yomu.modules.auth.datasource.driver-class-name=org.h2.Driver
yomu.modules.auth.datasource.username=sa
yomu.modules.auth.datasource.password=

yomu.modules.clan.datasource.url=jdbc:h2:file:./.localdb/clan;MODE=PostgreSQL;AUTO_SERVER=TRUE
yomu.modules.clan.datasource.driver-class-name=org.h2.Driver
yomu.modules.clan.datasource.username=sa
yomu.modules.clan.datasource.password=

yomu.modules.forum.datasource.url=jdbc:h2:file:./.localdb/forum;MODE=PostgreSQL;AUTO_SERVER=TRUE
yomu.modules.forum.datasource.driver-class-name=org.h2.Driver
yomu.modules.forum.datasource.username=sa
yomu.modules.forum.datasource.password=

yomu.modules.learning.datasource.url=jdbc:h2:file:./.localdb/learning;MODE=PostgreSQL;AUTO_SERVER=TRUE
yomu.modules.learning.datasource.driver-class-name=org.h2.Driver
yomu.modules.learning.datasource.username=sa
yomu.modules.learning.datasource.password=
